export const chats = [
  {title: 'React chat'},
  {title: 'Riot chat'},
  {title: 'Elite dangerous'},
  {title: 'Css chat'},
  {title: 'Marvel talks'},
  {title: 'DC talks'},
  {title: 'НЕновости'},
  {title: 'JS chat'},
  {title: 'FrontEnd Development'},
  {title: 'Close Encounters Corps'},
  {title: 'EG Pilots'},
  {title: 'Galactic Xenofobic Initiative'},
  {title: 'Eol Prou Group'},
  {title: 'Galnet'},
  {title: 'JS chat'},
  {title: 'JS chat'},
];

export const messages = [
  {sender: 'Someone', content: 'Hello'},
  {sender: 'Someone2', content: 'Lol kek'},
  {sender: 'Someone', content: 'Chat messages'},
  {sender: 'Beywer', content: 'My chat'},
  {sender: 'Beywer', content: 'My rules'},
  {sender: 'Sir. Mortimer', content: 'Hello'},
  {sender: 'Despero', content: 'Hola !'},
  {sender: 'Ispano delphino', content: 'La gracias por el pez'},
  {sender: 'Марвин', content: 'Когда горит лес, деревья горят вместе, Эмми.'},
  {sender: 'Someone', content: '4'},
  {sender: 'Someone', content: '8'},
  {sender: 'Someone', content: '15'},
  {sender: 'Someone', content: '16'},
  {sender: 'Someone', content: '23'},
  {sender: 'Someone', content: '42'},
];
