export const chats = [
  {title: 'React chat'},
  {title: 'Riot chat'},
  {title: 'Elite dangerous'},
  {title: 'Css chat'},
  {title: 'JS chat'},
  {title: 'JS chat'},
  {title: 'JS chat'},
  {title: 'JS chat'},
  {title: 'JS chat'},
  {title: 'JS chat'},
  {title: 'JS chat'},
  {title: 'JS chat'},
  {title: 'JS chat'},
  {title: 'JS chat'},
  {title: 'JS chat'},
  {title: 'JS chat'},
  {title: 'JS chat'},
  {title: 'JS chat'},
  {title: 'JS chat'},
  {title: 'JS chat'},
  {title: 'JS chat'},
  {title: 'JS chat'},
  {title: 'JS chat'},
];

export const messages = [
  {sender: 'Someone', content: 'Hello'},
  {sender: 'Someone', content: 'Lol kek'},
  {sender: 'Someone', content: 'Chat messages'},
  {sender: 'Beywer', content: 'My chat'},
  {sender: 'Beywer', content: 'My rules'},
  {sender: 'Someone', content: 'Hello'},
  {sender: 'Someone', content: 'Hello'},
  {sender: 'Someone', content: 'Hello'},
  {sender: 'Someone', content: 'Hello'},
  {sender: 'Someone', content: 'Hello'},
  {sender: 'Someone', content: 'Hello'},
  {sender: 'Someone', content: 'Hello'},
  {sender: 'Someone', content: 'Hello'},
  {sender: 'Someone', content: 'Hello'},
  {sender: 'Someone', content: 'Hello'},
  {sender: 'Someone', content: 'Hello'},
  {sender: 'Someone', content: 'Hello'},
];
